---
- hosts: all
  become: true
  tasks:
    - name: copy all host fqdn to databse server
      template:
        src: templates/server_list.j2
        dest: /etc/server_list.txt
        owner: automation
        group: automation
        mode: '0600'
        setype: net_conf_t
      when: inventory_hostname in groups['proxy']
