---
- hosts: webservers
  become: true
  tasks:
    - name: Sets the default boot target to multi-user
      file:
        src: /lib/systemd/system/multi-user.target
        dest: /etc/systemd/system/default.target
        state: link 
