---
# tasks file for sample-mysql
    - name: Create a new primary partition
      parted:
        device: /dev/sdb
        number: 1
        state: present
        flags: [ lvm ]
        part_end: 800MiB

    - name: Create volumne group vg_database
      lvg:
        vg: vg_database
        pvs: /dev/sdb1
        state: present
  
    - name: Create  logical volume lv_mysql
      lvol:
        vg: vg_database
        lv: lv_mysql
        size: 512m
        state: present


    - name: " FS format for new logical volume created"
      filesystem:
        fstype: xfs
        dev: /dev/vg_database/lv_mysql


    - name: " create mount directory /mnt/mysql_backup"
      file:
        path: /mnt/mysql_backup
        state: directory
        recurse: yes
        owner: root
        group: root


    - name: " mount FS lv_msql to /mnt/mysql_backups"
      mount:
        src: /dev/sdb1/vg_database/lv_mysql
        path: /mnt/mysql_backups
        fstype: xfs
        state: present




    - name: " install mysql packages with dependencies"
      dnf:        
        name:
          - mysql-server
          - python3-PyMySQL
        state: present

    - name: " start and enable mysql-deamon "
      systemd:
        name: mysqld
        state: started
        enabled: yes

    - name: " start and enable mysql-deamon "
      systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: " allow port 3306 on firewalld"
      firewalld:
        port: 3306/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - name: Create database user using hashed password with all database privileges
      mysql_user:
        name: root
        password: "{{database_password}}"
        priv: '*.*:ALL'
        state: present
        
    - name:
      template:
        src: templates/my.cnf.j2
        dest: /etc/my.cnf
      notify: "restart mysql-server"











